sonar.projectKey=xgate-sms-channel
sonar.projectName=xgate-sms-channel
sonar.working.directory=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\work\\Dynamics365-Solution\\XgateSmsChannel
sonar.pullrequest.cache.basepath=D:\\work\\Dynamics365-Solution\\XgateSmsChannel

F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.projectKey=xgate-sms-channel:F7B50068-3CA0-4BBB-9E37-3AA0B34F8056
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.projectName=XgateSmsChannel.Plugins
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.projectBaseDir=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.sourceEncoding=utf-8
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.tests=
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.sources=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\ChannelContracts\\Payload.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\ChannelContracts\\Response.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\ConsumingApplicationContracts\\DeliveryReport.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\DeliveryReportPlugin.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\InboundPlugin.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\JsonUtils.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\OutboundPlugin.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\ProviderContracts\\ProviderDeliveryReport.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\SmsCountOfStatus.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\SmsReceiveInfo.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\SmsRecipient.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\SmsRequest.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\SmsResponse.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\TokenRequest.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateContracts\\TokenResponse.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateGatewayException.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\XgateKey.snk",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\obj\\project.assets.json",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\obj\\XgateSmsChannel.Plugins.csproj.nuget.dgspec.json",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\obj\\Debug\\net471\\XgateSmsChannel.Plugins.sourcelink.json",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins\\obj\\Release\\net471\\XgateSmsChannel.Plugins.sourcelink.json"

F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.cs.analyzer.projectOutPaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\0"
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.cs.roslyn.reportFilePaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\0\\Issues.json"
F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.cs.scanner.telemetry=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\0\\Telemetry.json"

F7B50068-3CA0-4BBB-9E37-3AA0B34F8056.sonar.working.directory=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\.sonar\\mod0
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.projectKey=xgate-sms-channel:FCDF3C88-8165-439C-92EA-4535DFDB742D
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.projectName=XgateSmsChannel.Plugins.Tests
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.projectBaseDir=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.sourceEncoding=utf-8
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.sources=
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.tests=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\obj\\project.assets.json",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\obj\\XgateSmsChannel.Plugins.Tests.csproj.nuget.dgspec.json",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\obj\\Debug\\net471\\XgateSmsChannel.Plugins.Tests.sourcelink.json",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\DeliveryReportPluginTests.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\InboundPluginTests.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\JsonUtilsTests.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\OutboundPluginTests.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\PluginContextMockTests.cs",\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\PluginPipeline.cs"

FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.cs.analyzer.projectOutPaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\1"
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.cs.roslyn.reportFilePaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\1\\Issues.json"
FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.cs.scanner.telemetry=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\1\\Telemetry.json"

FCDF3C88-8165-439C-92EA-4535DFDB742D.sonar.working.directory=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\.sonar\\mod1
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.projectKey=xgate-sms-channel:9CF0806F-AB1D-4696-9505-7226513BFC5C
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.projectName=XgateSmsChannel.Plugins
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.projectBaseDir=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.sourceEncoding=utf-8
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.tests=
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.sources=\


9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.cs.analyzer.projectOutPaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\2"
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.cs.roslyn.reportFilePaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\2\\Issues.json"
9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.cs.scanner.telemetry=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\2\\Telemetry.json"

9CF0806F-AB1D-4696-9505-7226513BFC5C.sonar.working.directory=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\.sonar\\mod2
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.projectKey=xgate-sms-channel:F2BFFAB8-640F-4F41-84A7-C043332C33A9
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.projectName=XgateSmsChannel.Plugins.Tests
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.projectBaseDir=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.sourceEncoding=utf-8
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.sources=
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.tests=\


F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.cs.analyzer.projectOutPaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\3"
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.cs.roslyn.reportFilePaths=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\3\\Issues.json"
F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.cs.scanner.telemetry=\
"D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\3\\Telemetry.json"

F2BFFAB8-640F-4F41-84A7-C043332C33A9.sonar.working.directory=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\.sonarqube\\out\\.sonar\\mod3
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\TestResults\\coverage.opencover.xml
sonar.coverage.exclusions=**/*.Tests/**,**/*Tests.cs
sonar.exclusions=**/obj/**,**/bin/**,D:\\work\\Dynamics365-Solution\\XgateSmsChannel\\XgateSmsChannel.Plugins.Tests\\TestResults\\coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=F7B50068-3CA0-4BBB-9E37-3AA0B34F8056,FCDF3C88-8165-439C-92EA-4535DFDB742D,9CF0806F-AB1D-4696-9505-7226513BFC5C,F2BFFAB8-640F-4F41-84A7-C043332C33A9

