<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>XgateWhatsAppChannel.Plugins</AssemblyName>
    <RootNamespace>XgateWhatsAppChannel.Plugins</RootNamespace>
    <SignAssembly>True</SignAssembly>
    <DelaySign>True</DelaySign>
    <AssemblyOriginatorKeyFile>XgateKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.46" />
    <PackageReference Include="Microsoft.PowerApps.MSBuild.Plugin" Version="1.*" />
  </ItemGroup>
  <Target Name="GetProjectOutputPath" Returns="$(TargetPath)">
    <PropertyGroup>
      <ProjectOutputPath>$(TargetPath)</ProjectOutputPath>
    </PropertyGroup>
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutDir)$(TargetName).dll" DestinationFiles="$(MSBuildProjectDirectory)\..\src\PluginAssemblies\XgateWhatsAppChannelPlugins-710374E4-90C6-4A25-8215-D9F790AE55BB\XgateWhatsAppChannelPlugins.dll" />
  </Target>
</Project>